### PR TITLE
Test placeholder

### PR DESCRIPTION
**Pull request by Hemie143**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Testing the link to the placeholder with a fixed link within the frontend.

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks @Hemie143, I'll review the changes right away!

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Make sure all checks pass, only then you can merge the PR.

**Review by vanessa-cooper — APPROVED** [review]
Excellent job @Hemie143! You're now able to merge the PR.

**Comment by Hemie143** [comment]
In ItemPreview, the image is replaced by the placeholder if empty. 
Screenshot from 2022-08-17 23-26-21

**Pull request merged**
